### ISSUE TITLE
Disappointing 

### ISSUE THREAD

**Issue by coffpurpp** [Coders-After-Dark/Reskillable#124] opened 2018-06-14 06:32 UTC
I had high hopes for this mod but nothing is working properly. First off, I wanted to change the xp cost of vanilla stuff because it's a little too much for what I'm doing. Went to config, edited it properly, but didn't work. Likely this wasn't meant to be a feature but wow what a huge bummer. I also then added some modded items and they worked fine. My biggest issue is how broken it is. Sometimes when you unlock a skill, for instance, an iron pick. The iron pickaxe wont even break anything until you exit the game and rejoin. That's incredibly tedious. And worst of all, which makes this mod a huge no-no on top of that is the fact that the skills aren't working at all for me! 

Please know im not trying to shit on this mod, I love the concept, I wish it worked properly because I need it so so bad for my modpack, but I'm not sure why it isn't working! Maybe other mods are conflicting with it?

**Comment by pupnewfster** [comment] 2018-06-14 10:15
Are you using 1.7.0? Because the issue you are describing about having to relog sounds like the bug that I spent a few hours hotfixing for 1.7.1 the day the update came out.

Not quite sure what you mean about editting the vanilla stuff and it not working properly.

**Comment by coffpurpp** [comment] 2018-06-14 15:34
No I'm using 1.12.2. I have to relog to break stuff, and the abilities just dont work. 

Also you dont have to fix the vanilla stuff, though I'd prefer that, it was just something else I noticed.
Not to mention, like I said, I dont know if there is a certain mod that's conflicting with this one.

**Comment by Lanse505** [comment] 2018-06-14 15:35
He's asking for your version of Reskillable, not your Minecraft version @coffpurpp

**Comment by coffpurpp** [comment] 2018-06-14 16:25
Oh whoops. It's 1.7.1. Got the update yesterday to see if it fixed the problem. Didn't do anything from what I noticed.

**Comment by pupnewfster** [comment] 2018-06-14 18:24
That is odd given I had tested to make sure it fixed it.. But upon further testing you appear to be right that it is not working properly. I will work on a fix and try to release an update later today.

EDIT: Actually doing more testing because I forgot I had some weird test locks in my environment so the block I had attempted to break I did not meet the requirements of.

**Comment by pupnewfster** [comment] 2018-06-14 18:35
Ok so I am unable to reproduce the issue (using the 1.7.1 version of reskillable that is on curse). My suggestion to you is to double check that it updated properly because maybe something went wrong. If it still doesn't work are you using a server or single player (I tested it in single player just now).

**Comment by coffpurpp** [comment] 2018-06-14 20:41
Well I'll continue to look into it myself. I'll try it without other mods. I'll give an update soon.

**Comment by coffpurpp** [comment] 2018-06-14 21:26
I tried it in single player and without any other mods and everything works fine aside from abilities. Something I was curious about is are there any requirements for the mod to work? Skillable required something.

**Comment by pupnewfster** [comment] 2018-06-14 23:34
There are no other requirements. And what do you mean by the abilities not working? Could you not unlock them or did their effects not work?

**Comment by coffpurpp** [comment] 2018-06-14 23:46
The effects didn't work. I tried the hill-walker one. Figured I was just doing it wrong, so then I tried the golden weapon repair one (not sure of the name). That also didn't work, so then I tried the ender pearl damage one and that's when I was certain the abilities weren't working at all.

**Comment by pupnewfster** [comment] 2018-06-15 00:29
I will look into the abilities tomorrow to see if I can see if/what the issue with them is.

**Comment by coffpurpp** [comment] 2018-06-15 00:47
Good news is that now you dont have to use up your precious time for me on the skill thing. I figured it out just now! So far the only notable problem I have that I really care about is the configuration file. The vanilla item's xp required isn't changeable for some reason.

**Comment by coffpurpp** [comment] 2018-06-15 00:53
I figured the configuration file problem myself just now too. The mod is perfectly fine, but something in my modpack was messing with it. I've been testing on singleplayer is everything works fine. With that being said, sorry for dragging you guys into a me problem here. The mod is perfectly fine.

**Comment by pupnewfster** [comment] 2018-06-15 14:37
If you figure out what was messing with it and it is easy to reproduce let me know. If there ends up being some mod conflict would be nice to fix it. Who knows maybe it was just some fluke oddity. But I am glad you managed to get it working.

**Comment by coffpurpp** [comment] 2018-06-16 18:39
A little update: It was working for a bit and then it just suddenly stopped. All of my configuration settings were the same but didn't work in-game. Not to mention the pickaxe error came back. Weird stuff.

**Comment by coffpurpp** [comment] 2018-06-16 19:11
Not even the "fix" I had is working now. Either way, cant really use this for my modpack. It's stressful how inconsistent it is and is driving me and others away from the modpack unfortunately. I'll try this out again someday! I really needed this mod. Too bad im being cursed with tedious problems.

**Comment by pupnewfster** [comment] 2018-06-18 19:25
I believe the issues you have been having may actually be fixed by https://github.com/Coders-After-Dark/Reskillable/commit/bac7df5907cad9f555a352a24f459bb492fad45c  so be sure to check it out when a new version is posted. My guess is the version will be released tomorrow but it may be sometime later this week.

**Comment by Lanse505** [comment] 2018-07-15 16:50
Closing this since it's been 27 days without a response from opener and no other reports matching this has been made.

**Closed as completed by Lanse505** 2018-07-15 16:50 UTC
